version: 1
metadata:
  name: "Init - ScyCasino - Applications & OIDC"
entries:
  # Scopes
  - model: authentik_providers_oauth2.scopemapping
    id: scycasino-oauth2-openid
    identifiers:
      managed: goauthentik.io/providers/oauth2/scope-openid
    attrs:
      name: "ScyCasino OAuth Mapping: OpenID 'openid'"
      scope_name: openid
      expression: |
        return {}
  - model: authentik_providers_oauth2.scopemapping
    id: scycasino-oauth2-email
    identifiers:
      managed: goauthentik.io/providers/oauth2/scope-email
    attrs:
      name: "ScyCasino OAuth Mapping: OpenID 'email'"
      scope_name: email
      expression: |
        return {
            "email": request.user.email,
            "email_verified": True
        }
  - model: authentik_providers_oauth2.scopemapping
    id: scycasino-oauth2-profile
    identifiers:
      managed: goauthentik.io/providers/oauth2/scope-profile
    attrs:
      name: "ScyCasino OAuth Mapping: OpenID 'profile'"
      scope_name: profile
      expression: |
        return {
            "name": request.user.username,
            "given_name": request.user.username,
            "preferred_username": request.user.username,
            "groups": [group.name for group in request.user.ak_groups.all()],
        }
  - model: authentik_providers_oauth2.scopemapping
    id: scycasino-oauth2-offline_access
    identifiers:
      managed: goauthentik.io/providers/oauth2/scope-offline_access
    attrs:
      name: "ScyCasino OAuth Mapping: OpenID 'offline_access'"
      scope_name: offline_access
      expression: |
        return {}
  # Providers
  - model: authentik_providers_oauth2.oauth2provider
    state: present
    id: scycasino-oidc-provider
    identifiers:
      name: scycasino-oauth
    attrs:
      name: "ScyCasino OIDC Provider"
      client_id: "scycasino-auth-client-id"
      client_type: public
      redirect_uris: [{"matching_mode": "strict", "url": "http://localhost:4200"}]
      sub_mode: hashed_user_id
      issuer_mode: per_provider
      include_claims_in_id_token: true
      access_code_validity: minutes=1
      access_token_validity: minutes=5
      refresh_token_validity: days=30
      authorization_flow: !Find [ authentik_flows.flow, [ slug, default-provider-authorization-implicit-consent ] ]
      authentication_flow: !Find [ authentik_flows.flow, [ slug, default-authentication-flow ] ]
      invalidation_flow: !Find [ authentik_flows.flow, [ slug, default-invalidation-flow ] ]
      signing_key: !Find [ authentik_crypto.certificatekeypair, [ name, 'authentik Self-signed Certificate' ] ]
      property_mappings:
        - !KeyOf scycasino-oauth2-openid
        - !KeyOf scycasino-oauth2-email
        - !KeyOf scycasino-oauth2-profile
        - !KeyOf scycasino-oauth2-offline_access
  # Applications
  - model: authentik_core.application
    state: present
    id: scycasino-app
    identifiers:
      name: scycasino
    attrs:
      name: "ScyCasino"
      slug: "scycasino"
      provider: !KeyOf scycasino-oidc-provider