version: 1
metadata:
  name: "Init - ScyCasino - Applications & OIDC"
entries:
  # Scopes
  - model: authentik_providers_oauth2.scopemapping
    id: scycasino-oauth2-resource
    identifiers:
      name: "ScyCasino OAuth Mapping: Resource Access"
    attrs:
      scope_name: resource
      expression: |
        return {
            "name": request.user.username,
            "given_name": request.user.username,
            "preferred_username": request.user.username,
            "roles": [group.name for group in request.user.ak_groups.all()],
        }
  # Providers
  - model: authentik_providers_oauth2.oauth2provider
    state: present
    id: scycasino-oidc-provider
    identifiers:
      name: scycasino-oauth
    attrs:
      name: "ScyCasino OIDC Provider"
      client_id: "scycasino-auth-client-id"
      client_type: public
      redirect_uris: [{"matching_mode": "strict", "url": "http://localhost:4200"}]
      sub_mode: hashed_user_id
      issuer_mode: per_provider
      include_claims_in_id_token: true
      access_code_validity: minutes=1
      access_token_validity: minutes=5
      refresh_token_validity: days=30
      authorization_flow: !Find [ authentik_flows.flow, [ slug, default-provider-authorization-implicit-consent ] ]
      authentication_flow: !Find [ authentik_flows.flow, [ slug, default-authentication-flow ] ]
      invalidation_flow: !Find [ authentik_flows.flow, [ slug, default-invalidation-flow ] ]
      signing_key: !Find [ authentik_crypto.certificatekeypair, [ name, 'authentik Self-signed Certificate' ] ]
      property_mappings:
        - !Find [ authentik_providers_oauth2.scopemapping, [ managed, goauthentik.io/providers/oauth2/scope-openid ] ]
        - !Find [ authentik_providers_oauth2.scopemapping, [ managed, goauthentik.io/providers/oauth2/scope-offline_access ] ]
        - !KeyOf scycasino-oauth2-resource
  # Applications
  - model: authentik_core.application
    state: present
    id: scycasino-app
    identifiers:
      name: scycasino
    attrs:
      name: "ScyCasino"
      slug: "scycasino"
      provider: !KeyOf scycasino-oidc-provider